version: 2 # use CircleCI 2.0
jobs: 
  build: 
    
    working_directory: ~/vaadin-demo-bakery-app

    docker: 
      - image: circleci/openjdk:8u171-jdk

    steps: 

      - checkout 
      
      - run: mvn dependency:go-offline

      - run: mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v10.16.0"
      
      - run: mvn package
          
      - store_artifacts:
          path: /tmp/artifacts 
            
